### ISSUE TITLE
Support Schema Registry feature in Go Client

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar-client-go#344]
This is the Schema Registry design doc For Go Client: https://gist.github.com/wolfstudy/e0c9b349cd405715a9e04dd8658510bc

- [x] Basic classes on supporting schema (Primitive, PROTO, JSON, AVRO) #368
- [x] Support schema on Producer @wolfstudy #368
- [x] Support schema on Consumer @wolfstudy #368
- [ ] Add the schema version support - Multiple schema on a single topic (*) 
- [ ] Support schema on Reader
- [ ] Advanced Schema
   - [ ] KeyValue Schema
   - [ ] AutoSchema

**Comment by wolfstudy** [comment]
@merlimat @cckellogg @sijie PTAL thanks

**Comment by sijie** [comment]
@wolfstudy Can you also send the PIP to dev@ mailing list?

**Comment by wolfstudy** [comment]
> @wolfstudy Can you also send the PIP to dev@ mailing list?

Cool, will send it.
